version: '3.7'

volumes:
  local_sqlite_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mooja/metrics_tracker_django_local
    volumes:
      - .:/app
      - local_sqlite_data:/data
    ports:
      - "8000:8000"
    # entrypoint: /entrypoint.sh
    command: /start
    env_file:
      - ./.envs/.local/.django/.env
