#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


if [ ! -f "/data/db.sqlite3" ]; then 
    python /app/manage.py migrate --noinput
    python manage.py createcachetable
fi

python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8005 --chdir=/app