# Generated by Django 3.1.4 on 2021-01-04 23:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 1, 4))),
                ('num_hours', models.IntegerField()),
                ('tracker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to='tracker.tracker')),
            ],
        ),
    ]
