# Generated by Django 3.1.4 on 2021-01-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210114_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
