# Generated by Django 3.1.4 on 2021-01-17 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210114_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='target_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 16)),
        ),
    ]
