# Generated by Django 3.1.4 on 2021-02-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210118_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_count_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='target_session_count',
            field=models.IntegerField(default=1),
        ),
    ]
