# Generated by Django 3.1.4 on 2021-02-08 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210203_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_count_update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 19, 20, 5, 512334, tzinfo=utc)),
        ),
    ]
