# Generated by Django 3.1.4 on 2021-02-08 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_session_session_count_update_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_count_update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 19, 21, 22, 136414, tzinfo=utc)),
        ),
    ]
