# Generated by Django 3.1.3 on 2020-11-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to='tracker.tracker'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_type',
            field=models.CharField(choices=[('H', 'Hours Spent'), ('B', 'Boolean')], max_length=2),
        ),
    ]
