# Generated by Django 3.1.3 on 2020-11-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201125_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tracker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to='tracker.tracker'),
        ),
    ]
