# Generated by Django 3.1.4 on 2020-12-27 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20201207_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 27)),
        ),
    ]
