# Generated by Django 3.1.4 on 2020-12-28 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20201227_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 28)),
        ),
    ]
